# Generated by Django 4.0.4 on 2022-05-20 12:32

from django.db import migrations, models
import django.db.models.deletion
import kanbanBoard.models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanBoard', '0003_board_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kanbanBoard.board'),
        ),
    ]
