# Generated by Django 4.0.4 on 2022-06-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanBoard', '0004_task_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
